spring.application.name=chouse.game
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5433/chouse_game}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
services.poll.url=${POLL_SERVICE_URL:http://localhost:8081}
services.user.url=${USER_SERVICE_URL:http://localhost:8082}
